[package]
name = "wickdb"
version = "0.1.0"
authors = ["fullstop000 <fullstop1005@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3.8"
crossbeam-utils = "0.6.5"
libc = "0.2.0"
log = "0.4.6"
rand = "0.6.4"
hashbrown = "0.1.8"
snap = "0.2.5"
lazy_static = "1.3.0"
crc = "1.8.1"
fs2 = "0.4.3"